name: macos

on: [push]
env:
  PROTOC_VERSION: v3.11.2
jobs:
  compile:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: protocolbuffers/protobuf
        ref: ${{ env.PROTOC_VERSION }}
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: brew
      run: |
        brew update
        brew install autoconf automake libtool make unzip
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make install
      run: mkdir destdir && sudo make -j2 && sudo make install DESTDIR=$(pwd)/destdir
    - name: Upload build
      uses: actions/upload-artifact@v1
      with:
        name: protoc-${{ env.PROTOC_VERSION }}-macos
        path: ./destdir/usr/local