name: windows

on: [push]
env:
  PROTOC_VERSION: v3.11.2
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        repository: protocolbuffers/protobuf
        ref: ${{ env.PROTOC_VERSION }}
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - uses: ilammy/msvc-dev-cmd@v1
    - name: cmake & compile
      run: |
        cd cmake
        mkdir install
        cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install .
        nmake
    - name: Upload build
      uses: actions/upload-artifact@v1
      with:
        name: protoc-${{ env.PROTOC_VERSION }}-windows
        path: .